import { cudaGrammars } from "@/features/editor/cuda-grammar";
import type { LanguageId } from "@/features/editor/language";
import type { LanguageRegistration } from "shiki/core";

type LanguageDefinition = {
  /** Shown in the language picker. */
  readonly label: string;
  /** Alternative names accepted by the picker search. */
  readonly aliases: readonly string[];
  /** Grammar name passed to Shiki. Not always equal to the Pico id. */
  readonly shikiLang: string;
  /** Loads every registration the grammar depends on. */
  readonly load: () => Promise<LanguageRegistration[]>;
};

/**
 * What each of {@link LANGUAGE_IDS} is called and how its grammar is fetched.
 *
 * Split from the id list because this is the heavier half and nothing on the
 * first screen needs it: the picker lives in the chrome chunk, and the loaders
 * are only reached once the highlighter is already being fetched. Keeping the
 * loader beside the user-facing metadata still makes this the only table that
 * changes when a language is added, and `satisfies Record<LanguageId, ...>`
 * means an id without an entry here, or an entry without an id, is a compile
 * error rather than a language that quietly stops working.
 */
export const LANGUAGES = {
  bsl: {
    label: "1C (Enterprise)",
    aliases: ["1c"],
    shikiLang: "bsl",
    load: async () => (await import("@shikijs/langs/bsl")).default,
  },
  sdbl: {
    label: "1C (Query)",
    aliases: ["1c-query"],
    shikiLang: "sdbl",
    load: async () => (await import("@shikijs/langs/sdbl")).default,
  },
  abap: {
    label: "ABAP",
    aliases: [],
    shikiLang: "abap",
    load: async () => (await import("@shikijs/langs/abap")).default,
  },
  "actionscript-3": {
    label: "ActionScript",
    aliases: ["actionscript", "as3"],
    shikiLang: "actionscript-3",
    load: async () => (await import("@shikijs/langs/actionscript-3")).default,
  },
  ada: {
    label: "Ada",
    aliases: [],
    shikiLang: "ada",
    load: async () => (await import("@shikijs/langs/ada")).default,
  },
  "angular-html": {
    label: "Angular HTML",
    aliases: [],
    shikiLang: "angular-html",
    load: async () => (await import("@shikijs/langs/angular-html")).default,
  },
  "angular-ts": {
    label: "Angular TypeScript",
    aliases: [],
    shikiLang: "angular-ts",
    load: async () => (await import("@shikijs/langs/angular-ts")).default,
  },
  apache: {
    label: "Apache Conf",
    aliases: [],
    shikiLang: "apache",
    load: async () => (await import("@shikijs/langs/apache")).default,
  },
  apex: {
    label: "Apex",
    aliases: [],
    shikiLang: "apex",
    load: async () => (await import("@shikijs/langs/apex")).default,
  },
  apl: {
    label: "APL",
    aliases: [],
    shikiLang: "apl",
    load: async () => (await import("@shikijs/langs/apl")).default,
  },
  applescript: {
    label: "AppleScript",
    aliases: [],
    shikiLang: "applescript",
    load: async () => (await import("@shikijs/langs/applescript")).default,
  },
  ara: {
    label: "Ara",
    aliases: [],
    shikiLang: "ara",
    load: async () => (await import("@shikijs/langs/ara")).default,
  },
  asciidoc: {
    label: "AsciiDoc",
    aliases: ["adoc"],
    shikiLang: "asciidoc",
    load: async () => (await import("@shikijs/langs/asciidoc")).default,
  },
  razor: {
    label: "ASP.NET Razor",
    aliases: [],
    shikiLang: "razor",
    load: async () => (await import("@shikijs/langs/razor")).default,
  },
  asm: {
    label: "Assembly",
    aliases: [],
    shikiLang: "asm",
    load: async () => (await import("@shikijs/langs/asm")).default,
  },
  astro: {
    label: "Astro",
    aliases: [],
    shikiLang: "astro",
    load: async () => (await import("@shikijs/langs/astro")).default,
  },
  ahk: {
    label: "AutoHotkey",
    aliases: ["ahk1"],
    shikiLang: "ahk",
    load: async () => (await import("@shikijs/langs/ahk")).default,
  },
  ahk2: {
    label: "AutoHotkey2",
    aliases: [],
    shikiLang: "ahk2",
    load: async () => (await import("@shikijs/langs/ahk2")).default,
  },
  awk: {
    label: "AWK",
    aliases: [],
    shikiLang: "awk",
    load: async () => (await import("@shikijs/langs/awk")).default,
  },
  ballerina: {
    label: "Ballerina",
    aliases: [],
    shikiLang: "ballerina",
    load: async () => (await import("@shikijs/langs/ballerina")).default,
  },
  bat: {
    label: "Batch File",
    aliases: ["batch", "cmd"],
    shikiLang: "bat",
    load: async () => (await import("@shikijs/langs/bat")).default,
  },
  beancount: {
    label: "Beancount",
    aliases: [],
    shikiLang: "beancount",
    load: async () => (await import("@shikijs/langs/beancount")).default,
  },
  berry: {
    label: "Berry",
    aliases: ["be"],
    shikiLang: "berry",
    load: async () => (await import("@shikijs/langs/berry")).default,
  },
  bibtex: {
    label: "BibTeX",
    aliases: [],
    shikiLang: "bibtex",
    load: async () => (await import("@shikijs/langs/bibtex")).default,
  },
  bicep: {
    label: "Bicep",
    aliases: [],
    shikiLang: "bicep",
    load: async () => (await import("@shikijs/langs/bicep")).default,
  },
  bird2: {
    label: "BIRD2 Configuration",
    aliases: ["bird"],
    shikiLang: "bird2",
    load: async () => (await import("@shikijs/langs/bird2")).default,
  },
  blade: {
    label: "Blade",
    aliases: [],
    shikiLang: "blade",
    load: async () => (await import("@shikijs/langs/blade")).default,
  },
  c: {
    label: "C",
    aliases: [],
    shikiLang: "c",
    load: async () => (await import("@shikijs/langs/c")).default,
  },
  csharp: {
    label: "C#",
    aliases: ["c#", "cs"],
    shikiLang: "csharp",
    load: async () => (await import("@shikijs/langs/csharp")).default,
  },
  cpp: {
    label: "C++",
    aliases: ["c++"],
    shikiLang: "cpp",
    load: async () => (await import("@shikijs/langs/cpp")).default,
  },
  c3: {
    label: "C3",
    aliases: [],
    shikiLang: "c3",
    load: async () => (await import("@shikijs/langs/c3")).default,
  },
  cadence: {
    label: "Cadence",
    aliases: ["cdc"],
    shikiLang: "cadence",
    load: async () => (await import("@shikijs/langs/cadence")).default,
  },
  cairo: {
    label: "Cairo",
    aliases: [],
    shikiLang: "cairo",
    load: async () => (await import("@shikijs/langs/cairo")).default,
  },
  chapel: {
    label: "Chapel",
    aliases: ["chpl"],
    shikiLang: "chapel",
    load: async () => (await import("@shikijs/langs/chapel")).default,
  },
  clarity: {
    label: "Clarity",
    aliases: [],
    shikiLang: "clarity",
    load: async () => (await import("@shikijs/langs/clarity")).default,
  },
  clojure: {
    label: "Clojure",
    aliases: ["clj"],
    shikiLang: "clojure",
    load: async () => (await import("@shikijs/langs/clojure")).default,
  },
  soy: {
    label: "Closure Templates",
    aliases: ["closure-templates"],
    shikiLang: "soy",
    load: async () => (await import("@shikijs/langs/soy")).default,
  },
  cmake: {
    label: "CMake",
    aliases: [],
    shikiLang: "cmake",
    load: async () => (await import("@shikijs/langs/cmake")).default,
  },
  cobol: {
    label: "COBOL",
    aliases: [],
    shikiLang: "cobol",
    load: async () => (await import("@shikijs/langs/cobol")).default,
  },
  codeowners: {
    label: "CODEOWNERS",
    aliases: [],
    shikiLang: "codeowners",
    load: async () => (await import("@shikijs/langs/codeowners")).default,
  },
  codeql: {
    label: "CodeQL",
    aliases: ["ql"],
    shikiLang: "codeql",
    load: async () => (await import("@shikijs/langs/codeql")).default,
  },
  coffee: {
    label: "CoffeeScript",
    aliases: ["coffeescript"],
    shikiLang: "coffee",
    load: async () => (await import("@shikijs/langs/coffee")).default,
  },
  "common-lisp": {
    label: "Common Lisp",
    aliases: ["lisp"],
    shikiLang: "common-lisp",
    load: async () => (await import("@shikijs/langs/common-lisp")).default,
  },
  crystal: {
    label: "Crystal",
    aliases: [],
    shikiLang: "crystal",
    load: async () => (await import("@shikijs/langs/crystal")).default,
  },
  css: {
    label: "CSS",
    aliases: [],
    shikiLang: "css",
    load: async () => (await import("@shikijs/langs/css")).default,
  },
  csv: {
    label: "CSV",
    aliases: [],
    shikiLang: "csv",
    load: async () => (await import("@shikijs/langs/csv")).default,
  },
  cuda: {
    label: "CUDA",
    aliases: ["cu"],
    shikiLang: "cuda",
    load: async () => [...(await import("@shikijs/langs/cpp")).default, ...cudaGrammars],
  },
  cue: {
    label: "CUE",
    aliases: [],
    shikiLang: "cue",
    load: async () => (await import("@shikijs/langs/cue")).default,
  },
  cypher: {
    label: "Cypher",
    aliases: ["cql"],
    shikiLang: "cypher",
    load: async () => (await import("@shikijs/langs/cypher")).default,
  },
  d: {
    label: "D",
    aliases: [],
    shikiLang: "d",
    load: async () => (await import("@shikijs/langs/d")).default,
  },
  dart: {
    label: "Dart",
    aliases: [],
    shikiLang: "dart",
    load: async () => (await import("@shikijs/langs/dart")).default,
  },
  dax: {
    label: "DAX",
    aliases: [],
    shikiLang: "dax",
    load: async () => (await import("@shikijs/langs/dax")).default,
  },
  desktop: {
    label: "Desktop",
    aliases: [],
    shikiLang: "desktop",
    load: async () => (await import("@shikijs/langs/desktop")).default,
  },
  diff: {
    label: "Diff",
    aliases: [],
    shikiLang: "diff",
    load: async () => (await import("@shikijs/langs/diff")).default,
  },
  docker: {
    label: "Dockerfile",
    aliases: ["dockerfile"],
    shikiLang: "docker",
    load: async () => (await import("@shikijs/langs/docker")).default,
  },
  dotenv: {
    label: "dotEnv",
    aliases: [],
    shikiLang: "dotenv",
    load: async () => (await import("@shikijs/langs/dotenv")).default,
  },
  "dream-maker": {
    label: "Dream Maker",
    aliases: [],
    shikiLang: "dream-maker",
    load: async () => (await import("@shikijs/langs/dream-maker")).default,
  },
  edge: {
    label: "Edge",
    aliases: [],
    shikiLang: "edge",
    load: async () => (await import("@shikijs/langs/edge")).default,
  },
  elixir: {
    label: "Elixir",
    aliases: [],
    shikiLang: "elixir",
    load: async () => (await import("@shikijs/langs/elixir")).default,
  },
  elm: {
    label: "Elm",
    aliases: [],
    shikiLang: "elm",
    load: async () => (await import("@shikijs/langs/elm")).default,
  },
  "emacs-lisp": {
    label: "Emacs Lisp",
    aliases: ["elisp"],
    shikiLang: "emacs-lisp",
    load: async () => (await import("@shikijs/langs/emacs-lisp")).default,
  },
  erb: {
    label: "ERB",
    aliases: [],
    shikiLang: "erb",
    load: async () => (await import("@shikijs/langs/erb")).default,
  },
  erlang: {
    label: "Erlang",
    aliases: ["erl"],
    shikiLang: "erlang",
    load: async () => (await import("@shikijs/langs/erlang")).default,
  },
  fsharp: {
    label: "F#",
    aliases: ["f#", "fs"],
    shikiLang: "fsharp",
    load: async () => (await import("@shikijs/langs/fsharp")).default,
  },
  fennel: {
    label: "Fennel",
    aliases: [],
    shikiLang: "fennel",
    load: async () => (await import("@shikijs/langs/fennel")).default,
  },
  fish: {
    label: "Fish",
    aliases: [],
    shikiLang: "fish",
    load: async () => (await import("@shikijs/langs/fish")).default,
  },
  fluent: {
    label: "Fluent",
    aliases: ["ftl"],
    shikiLang: "fluent",
    load: async () => (await import("@shikijs/langs/fluent")).default,
  },
  "fortran-fixed-form": {
    label: "Fortran (Fixed Form)",
    aliases: ["f", "for", "f77"],
    shikiLang: "fortran-fixed-form",
    load: async () => (await import("@shikijs/langs/fortran-fixed-form")).default,
  },
  "fortran-free-form": {
    label: "Fortran (Free Form)",
    aliases: ["f90", "f95", "f03", "f08", "f18"],
    shikiLang: "fortran-free-form",
    load: async () => (await import("@shikijs/langs/fortran-free-form")).default,
  },
  gdresource: {
    label: "GDResource",
    aliases: ["tscn", "tres"],
    shikiLang: "gdresource",
    load: async () => (await import("@shikijs/langs/gdresource")).default,
  },
  gdscript: {
    label: "GDScript",
    aliases: ["gd"],
    shikiLang: "gdscript",
    load: async () => (await import("@shikijs/langs/gdscript")).default,
  },
  gdshader: {
    label: "GDShader",
    aliases: [],
    shikiLang: "gdshader",
    load: async () => (await import("@shikijs/langs/gdshader")).default,
  },
  genie: {
    label: "Genie",
    aliases: [],
    shikiLang: "genie",
    load: async () => (await import("@shikijs/langs/genie")).default,
  },
  po: {
    label: "Gettext PO",
    aliases: ["pot", "potx"],
    shikiLang: "po",
    load: async () => (await import("@shikijs/langs/po")).default,
  },
  gherkin: {
    label: "Gherkin",
    aliases: [],
    shikiLang: "gherkin",
    load: async () => (await import("@shikijs/langs/gherkin")).default,
  },
  "git-commit": {
    label: "Git Commit Message",
    aliases: [],
    shikiLang: "git-commit",
    load: async () => (await import("@shikijs/langs/git-commit")).default,
  },
  "git-rebase": {
    label: "Git Rebase Message",
    aliases: [],
    shikiLang: "git-rebase",
    load: async () => (await import("@shikijs/langs/git-rebase")).default,
  },
  gleam: {
    label: "Gleam",
    aliases: [],
    shikiLang: "gleam",
    load: async () => (await import("@shikijs/langs/gleam")).default,
  },
  "glimmer-js": {
    label: "Glimmer JS",
    aliases: ["gjs"],
    shikiLang: "glimmer-js",
    load: async () => (await import("@shikijs/langs/glimmer-js")).default,
  },
  "glimmer-ts": {
    label: "Glimmer TS",
    aliases: ["gts"],
    shikiLang: "glimmer-ts",
    load: async () => (await import("@shikijs/langs/glimmer-ts")).default,
  },
  glsl: {
    label: "GLSL",
    aliases: [],
    shikiLang: "glsl",
    load: async () => (await import("@shikijs/langs/glsl")).default,
  },
  gn: {
    label: "GN",
    aliases: [],
    shikiLang: "gn",
    load: async () => (await import("@shikijs/langs/gn")).default,
  },
  smalltalk: {
    label: "GNU Smalltalk",
    aliases: [],
    shikiLang: "smalltalk",
    load: async () => (await import("@shikijs/langs/smalltalk")).default,
  },
  gnuplot: {
    label: "Gnuplot",
    aliases: [],
    shikiLang: "gnuplot",
    load: async () => (await import("@shikijs/langs/gnuplot")).default,
  },
  go: {
    label: "Go",
    aliases: [],
    shikiLang: "go",
    load: async () => (await import("@shikijs/langs/go")).default,
  },
  graphql: {
    label: "GraphQL",
    aliases: ["gql"],
    shikiLang: "graphql",
    load: async () => (await import("@shikijs/langs/graphql")).default,
  },
  groovy: {
    label: "Groovy",
    aliases: [],
    shikiLang: "groovy",
    load: async () => (await import("@shikijs/langs/groovy")).default,
  },
  hack: {
    label: "Hack",
    aliases: [],
    shikiLang: "hack",
    load: async () => (await import("@shikijs/langs/hack")).default,
  },
  handlebars: {
    label: "Handlebars",
    aliases: ["hbs"],
    shikiLang: "handlebars",
    load: async () => (await import("@shikijs/langs/handlebars")).default,
  },
  hcl: {
    label: "HashiCorp HCL",
    aliases: [],
    shikiLang: "hcl",
    load: async () => (await import("@shikijs/langs/hcl")).default,
  },
  haskell: {
    label: "Haskell",
    aliases: ["hs"],
    shikiLang: "haskell",
    load: async () => (await import("@shikijs/langs/haskell")).default,
  },
  haxe: {
    label: "Haxe",
    aliases: [],
    shikiLang: "haxe",
    load: async () => (await import("@shikijs/langs/haxe")).default,
  },
  hjson: {
    label: "Hjson",
    aliases: [],
    shikiLang: "hjson",
    load: async () => (await import("@shikijs/langs/hjson")).default,
  },
  hlsl: {
    label: "HLSL",
    aliases: [],
    shikiLang: "hlsl",
    load: async () => (await import("@shikijs/langs/hlsl")).default,
  },
  html: {
    label: "HTML",
    aliases: [],
    shikiLang: "html",
    load: async () => (await import("@shikijs/langs/html")).default,
  },
  "html-derivative": {
    label: "HTML (Derivative)",
    aliases: [],
    shikiLang: "html-derivative",
    load: async () => (await import("@shikijs/langs/html-derivative")).default,
  },
  http: {
    label: "HTTP",
    aliases: [],
    shikiLang: "http",
    load: async () => (await import("@shikijs/langs/http")).default,
  },
  hurl: {
    label: "Hurl",
    aliases: [],
    shikiLang: "hurl",
    load: async () => (await import("@shikijs/langs/hurl")).default,
  },
  hxml: {
    label: "HXML",
    aliases: [],
    shikiLang: "hxml",
    load: async () => (await import("@shikijs/langs/hxml")).default,
  },
  hy: {
    label: "Hy",
    aliases: [],
    shikiLang: "hy",
    load: async () => (await import("@shikijs/langs/hy")).default,
  },
  imba: {
    label: "Imba",
    aliases: [],
    shikiLang: "imba",
    load: async () => (await import("@shikijs/langs/imba")).default,
  },
  ini: {
    label: "INI",
    aliases: ["properties"],
    shikiLang: "ini",
    load: async () => (await import("@shikijs/langs/ini")).default,
  },
  java: {
    label: "Java",
    aliases: [],
    shikiLang: "java",
    load: async () => (await import("@shikijs/langs/java")).default,
  },
  js: {
    label: "JavaScript",
    aliases: ["javascript", "js", "cjs", "mjs"],
    shikiLang: "javascript",
    load: async () => (await import("@shikijs/langs/javascript")).default,
  },
  jinja: {
    label: "Jinja",
    aliases: [],
    shikiLang: "jinja",
    load: async () => (await import("@shikijs/langs/jinja")).default,
  },
  jison: {
    label: "Jison",
    aliases: [],
    shikiLang: "jison",
    load: async () => (await import("@shikijs/langs/jison")).default,
  },
  json: {
    label: "JSON",
    aliases: [],
    shikiLang: "json",
    load: async () => (await import("@shikijs/langs/json")).default,
  },
  jsonl: {
    label: "JSON Lines",
    aliases: [],
    shikiLang: "jsonl",
    load: async () => (await import("@shikijs/langs/jsonl")).default,
  },
  jsonc: {
    label: "JSON with Comments",
    aliases: [],
    shikiLang: "jsonc",
    load: async () => (await import("@shikijs/langs/jsonc")).default,
  },
  json5: {
    label: "JSON5",
    aliases: [],
    shikiLang: "json5",
    load: async () => (await import("@shikijs/langs/json5")).default,
  },
  jsonnet: {
    label: "Jsonnet",
    aliases: [],
    shikiLang: "jsonnet",
    load: async () => (await import("@shikijs/langs/jsonnet")).default,
  },
  jssm: {
    label: "JSSM",
    aliases: ["fsl"],
    shikiLang: "jssm",
    load: async () => (await import("@shikijs/langs/jssm")).default,
  },
  jsx: {
    label: "JSX",
    aliases: [],
    shikiLang: "jsx",
    load: async () => (await import("@shikijs/langs/jsx")).default,
  },
  julia: {
    label: "Julia",
    aliases: ["jl"],
    shikiLang: "julia",
    load: async () => (await import("@shikijs/langs/julia")).default,
  },
  just: {
    label: "Just",
    aliases: ["justfile"],
    shikiLang: "just",
    load: async () => (await import("@shikijs/langs/just")).default,
  },
  kdl: {
    label: "KDL",
    aliases: [],
    shikiLang: "kdl",
    load: async () => (await import("@shikijs/langs/kdl")).default,
  },
  kotlin: {
    label: "Kotlin",
    aliases: ["kt", "kts"],
    shikiLang: "kotlin",
    load: async () => (await import("@shikijs/langs/kotlin")).default,
  },
  kusto: {
    label: "Kusto",
    aliases: ["kql"],
    shikiLang: "kusto",
    load: async () => (await import("@shikijs/langs/kusto")).default,
  },
  latex: {
    label: "LaTeX",
    aliases: [],
    shikiLang: "latex",
    load: async () => (await import("@shikijs/langs/latex")).default,
  },
  lean: {
    label: "Lean 4",
    aliases: ["lean4"],
    shikiLang: "lean",
    load: async () => (await import("@shikijs/langs/lean")).default,
  },
  less: {
    label: "Less",
    aliases: [],
    shikiLang: "less",
    load: async () => (await import("@shikijs/langs/less")).default,
  },
  liquid: {
    label: "Liquid",
    aliases: [],
    shikiLang: "liquid",
    load: async () => (await import("@shikijs/langs/liquid")).default,
  },
  llvm: {
    label: "LLVM IR",
    aliases: [],
    shikiLang: "llvm",
    load: async () => (await import("@shikijs/langs/llvm")).default,
  },
  log: {
    label: "Log file",
    aliases: [],
    shikiLang: "log",
    load: async () => (await import("@shikijs/langs/log")).default,
  },
  logo: {
    label: "Logo",
    aliases: [],
    shikiLang: "logo",
    load: async () => (await import("@shikijs/langs/logo")).default,
  },
  lua: {
    label: "Lua",
    aliases: [],
    shikiLang: "lua",
    load: async () => (await import("@shikijs/langs/lua")).default,
  },
  luau: {
    label: "Luau",
    aliases: [],
    shikiLang: "luau",
    load: async () => (await import("@shikijs/langs/luau")).default,
  },
  make: {
    label: "Makefile",
    aliases: ["makefile"],
    shikiLang: "make",
    load: async () => (await import("@shikijs/langs/make")).default,
  },
  markdown: {
    label: "Markdown",
    aliases: ["md"],
    shikiLang: "markdown",
    load: async () => (await import("@shikijs/langs/markdown")).default,
  },
  marko: {
    label: "Marko",
    aliases: [],
    shikiLang: "marko",
    load: async () => (await import("@shikijs/langs/marko")).default,
  },
  matlab: {
    label: "MATLAB",
    aliases: [],
    shikiLang: "matlab",
    load: async () => (await import("@shikijs/langs/matlab")).default,
  },
  mdc: {
    label: "MDC",
    aliases: [],
    shikiLang: "mdc",
    load: async () => (await import("@shikijs/langs/mdc")).default,
  },
  mdx: {
    label: "MDX",
    aliases: [],
    shikiLang: "mdx",
    load: async () => (await import("@shikijs/langs/mdx")).default,
  },
  mermaid: {
    label: "Mermaid",
    aliases: ["mmd"],
    shikiLang: "mermaid",
    load: async () => (await import("@shikijs/langs/mermaid")).default,
  },
  mipsasm: {
    label: "MIPS Assembly",
    aliases: ["mips"],
    shikiLang: "mipsasm",
    load: async () => (await import("@shikijs/langs/mipsasm")).default,
  },
  mojo: {
    label: "Mojo",
    aliases: [],
    shikiLang: "mojo",
    load: async () => (await import("@shikijs/langs/mojo")).default,
  },
  moonbit: {
    label: "MoonBit",
    aliases: ["mbt", "mbti"],
    shikiLang: "moonbit",
    load: async () => (await import("@shikijs/langs/moonbit")).default,
  },
  move: {
    label: "Move",
    aliases: [],
    shikiLang: "move",
    load: async () => (await import("@shikijs/langs/move")).default,
  },
  narrat: {
    label: "Narrat Language",
    aliases: ["nar"],
    shikiLang: "narrat",
    load: async () => (await import("@shikijs/langs/narrat")).default,
  },
  nextflow: {
    label: "Nextflow",
    aliases: ["nf"],
    shikiLang: "nextflow",
    load: async () => (await import("@shikijs/langs/nextflow")).default,
  },
  "nextflow-groovy": {
    label: "Nextflow Groovy",
    aliases: [],
    shikiLang: "nextflow-groovy",
    load: async () => (await import("@shikijs/langs/nextflow-groovy")).default,
  },
  nginx: {
    label: "Nginx",
    aliases: [],
    shikiLang: "nginx",
    load: async () => (await import("@shikijs/langs/nginx")).default,
  },
  nim: {
    label: "Nim",
    aliases: [],
    shikiLang: "nim",
    load: async () => (await import("@shikijs/langs/nim")).default,
  },
  nix: {
    label: "Nix",
    aliases: [],
    shikiLang: "nix",
    load: async () => (await import("@shikijs/langs/nix")).default,
  },
  nsis: {
    label: "NSIS",
    aliases: [],
    shikiLang: "nsis",
    load: async () => (await import("@shikijs/langs/nsis")).default,
  },
  nushell: {
    label: "nushell",
    aliases: ["nu"],
    shikiLang: "nushell",
    load: async () => (await import("@shikijs/langs/nushell")).default,
  },
  "objective-c": {
    label: "Objective-C",
    aliases: ["objc"],
    shikiLang: "objective-c",
    load: async () => (await import("@shikijs/langs/objective-c")).default,
  },
  "objective-cpp": {
    label: "Objective-C++",
    aliases: [],
    shikiLang: "objective-cpp",
    load: async () => (await import("@shikijs/langs/objective-cpp")).default,
  },
  ocaml: {
    label: "OCaml",
    aliases: [],
    shikiLang: "ocaml",
    load: async () => (await import("@shikijs/langs/ocaml")).default,
  },
  odin: {
    label: "Odin",
    aliases: [],
    shikiLang: "odin",
    load: async () => (await import("@shikijs/langs/odin")).default,
  },
  openscad: {
    label: "OpenSCAD",
    aliases: ["scad"],
    shikiLang: "openscad",
    load: async () => (await import("@shikijs/langs/openscad")).default,
  },
  org: {
    label: "Org Markup",
    aliases: [],
    shikiLang: "org",
    load: async () => (await import("@shikijs/langs/org")).default,
  },
  pascal: {
    label: "Pascal",
    aliases: [],
    shikiLang: "pascal",
    load: async () => (await import("@shikijs/langs/pascal")).default,
  },
  perl: {
    label: "Perl",
    aliases: [],
    shikiLang: "perl",
    load: async () => (await import("@shikijs/langs/perl")).default,
  },
  php: {
    label: "PHP",
    aliases: [],
    shikiLang: "php",
    load: async () => (await import("@shikijs/langs/php")).default,
  },
  pkl: {
    label: "Pkl",
    aliases: [],
    shikiLang: "pkl",
    load: async () => (await import("@shikijs/langs/pkl")).default,
  },
  plsql: {
    label: "PL/SQL",
    aliases: [],
    shikiLang: "plsql",
    load: async () => (await import("@shikijs/langs/plsql")).default,
  },
  polar: {
    label: "Polar",
    aliases: [],
    shikiLang: "polar",
    load: async () => (await import("@shikijs/langs/polar")).default,
  },
  postcss: {
    label: "PostCSS",
    aliases: [],
    shikiLang: "postcss",
    load: async () => (await import("@shikijs/langs/postcss")).default,
  },
  powerquery: {
    label: "PowerQuery",
    aliases: [],
    shikiLang: "powerquery",
    load: async () => (await import("@shikijs/langs/powerquery")).default,
  },
  powershell: {
    label: "PowerShell",
    aliases: ["ps", "ps1", "pwsh"],
    shikiLang: "powershell",
    load: async () => (await import("@shikijs/langs/powershell")).default,
  },
  prisma: {
    label: "Prisma",
    aliases: [],
    shikiLang: "prisma",
    load: async () => (await import("@shikijs/langs/prisma")).default,
  },
  prolog: {
    label: "Prolog",
    aliases: [],
    shikiLang: "prolog",
    load: async () => (await import("@shikijs/langs/prolog")).default,
  },
  proto: {
    label: "Protocol Buffer 3",
    aliases: ["protobuf"],
    shikiLang: "proto",
    load: async () => (await import("@shikijs/langs/proto")).default,
  },
  pug: {
    label: "Pug",
    aliases: ["jade"],
    shikiLang: "pug",
    load: async () => (await import("@shikijs/langs/pug")).default,
  },
  puppet: {
    label: "Puppet",
    aliases: [],
    shikiLang: "puppet",
    load: async () => (await import("@shikijs/langs/puppet")).default,
  },
  purescript: {
    label: "PureScript",
    aliases: [],
    shikiLang: "purescript",
    load: async () => (await import("@shikijs/langs/purescript")).default,
  },
  python: {
    label: "Python",
    aliases: ["py"],
    shikiLang: "python",
    load: async () => (await import("@shikijs/langs/python")).default,
  },
  qml: {
    label: "QML",
    aliases: [],
    shikiLang: "qml",
    load: async () => (await import("@shikijs/langs/qml")).default,
  },
  qmldir: {
    label: "QML Directory",
    aliases: [],
    shikiLang: "qmldir",
    load: async () => (await import("@shikijs/langs/qmldir")).default,
  },
  qss: {
    label: "Qt Style Sheets",
    aliases: [],
    shikiLang: "qss",
    load: async () => (await import("@shikijs/langs/qss")).default,
  },
  r: {
    label: "R",
    aliases: [],
    shikiLang: "r",
    load: async () => (await import("@shikijs/langs/r")).default,
  },
  racket: {
    label: "Racket",
    aliases: [],
    shikiLang: "racket",
    load: async () => (await import("@shikijs/langs/racket")).default,
  },
  raku: {
    label: "Raku",
    aliases: ["perl6"],
    shikiLang: "raku",
    load: async () => (await import("@shikijs/langs/raku")).default,
  },
  rbs: {
    label: "RBS",
    aliases: ["ruby-signature"],
    shikiLang: "rbs",
    load: async () => (await import("@shikijs/langs/rbs")).default,
  },
  regexp: {
    label: "RegExp",
    aliases: ["regex"],
    shikiLang: "regexp",
    load: async () => (await import("@shikijs/langs/regexp")).default,
  },
  rel: {
    label: "Rel",
    aliases: [],
    shikiLang: "rel",
    load: async () => (await import("@shikijs/langs/rel")).default,
  },
  rst: {
    label: "reStructuredText",
    aliases: [],
    shikiLang: "rst",
    load: async () => (await import("@shikijs/langs/rst")).default,
  },
  riscv: {
    label: "RISC-V",
    aliases: [],
    shikiLang: "riscv",
    load: async () => (await import("@shikijs/langs/riscv")).default,
  },
  coq: {
    label: "Rocq",
    aliases: [],
    shikiLang: "coq",
    load: async () => (await import("@shikijs/langs/coq")).default,
  },
  ron: {
    label: "RON",
    aliases: [],
    shikiLang: "ron",
    load: async () => (await import("@shikijs/langs/ron")).default,
  },
  rosmsg: {
    label: "ROS Interface",
    aliases: [],
    shikiLang: "rosmsg",
    load: async () => (await import("@shikijs/langs/rosmsg")).default,
  },
  ruby: {
    label: "Ruby",
    aliases: ["rb"],
    shikiLang: "ruby",
    load: async () => (await import("@shikijs/langs/ruby")).default,
  },
  haml: {
    label: "Ruby Haml",
    aliases: [],
    shikiLang: "haml",
    load: async () => (await import("@shikijs/langs/haml")).default,
  },
  rust: {
    label: "Rust",
    aliases: ["rs"],
    shikiLang: "rust",
    load: async () => (await import("@shikijs/langs/rust")).default,
  },
  sas: {
    label: "SAS",
    aliases: [],
    shikiLang: "sas",
    load: async () => (await import("@shikijs/langs/sas")).default,
  },
  sass: {
    label: "Sass",
    aliases: [],
    shikiLang: "sass",
    load: async () => (await import("@shikijs/langs/sass")).default,
  },
  scala: {
    label: "Scala",
    aliases: [],
    shikiLang: "scala",
    load: async () => (await import("@shikijs/langs/scala")).default,
  },
  scheme: {
    label: "Scheme",
    aliases: [],
    shikiLang: "scheme",
    load: async () => (await import("@shikijs/langs/scheme")).default,
  },
  scss: {
    label: "SCSS",
    aliases: [],
    shikiLang: "scss",
    load: async () => (await import("@shikijs/langs/scss")).default,
  },
  shaderlab: {
    label: "ShaderLab",
    aliases: ["shader"],
    shikiLang: "shaderlab",
    load: async () => (await import("@shikijs/langs/shaderlab")).default,
  },
  shellscript: {
    label: "Shell",
    aliases: ["bash", "sh", "shell", "zsh"],
    shikiLang: "shellscript",
    load: async () => (await import("@shikijs/langs/shellscript")).default,
  },
  shellsession: {
    label: "Shell Session",
    aliases: ["console"],
    shikiLang: "shellsession",
    load: async () => (await import("@shikijs/langs/shellsession")).default,
  },
  smithy: {
    label: "Smithy",
    aliases: [],
    shikiLang: "smithy",
    load: async () => (await import("@shikijs/langs/smithy")).default,
  },
  solidity: {
    label: "Solidity",
    aliases: [],
    shikiLang: "solidity",
    load: async () => (await import("@shikijs/langs/solidity")).default,
  },
  sparql: {
    label: "SPARQL",
    aliases: [],
    shikiLang: "sparql",
    load: async () => (await import("@shikijs/langs/sparql")).default,
  },
  splunk: {
    label: "Splunk Query Language",
    aliases: ["spl"],
    shikiLang: "splunk",
    load: async () => (await import("@shikijs/langs/splunk")).default,
  },
  sql: {
    label: "SQL",
    aliases: [],
    shikiLang: "sql",
    load: async () => (await import("@shikijs/langs/sql")).default,
  },
  "ssh-config": {
    label: "SSH Config",
    aliases: [],
    shikiLang: "ssh-config",
    load: async () => (await import("@shikijs/langs/ssh-config")).default,
  },
  stata: {
    label: "Stata",
    aliases: [],
    shikiLang: "stata",
    load: async () => (await import("@shikijs/langs/stata")).default,
  },
  stylus: {
    label: "Stylus",
    aliases: ["styl"],
    shikiLang: "stylus",
    load: async () => (await import("@shikijs/langs/stylus")).default,
  },
  surrealql: {
    label: "SurrealQL",
    aliases: ["surql"],
    shikiLang: "surrealql",
    load: async () => (await import("@shikijs/langs/surrealql")).default,
  },
  svelte: {
    label: "Svelte",
    aliases: [],
    shikiLang: "svelte",
    load: async () => (await import("@shikijs/langs/svelte")).default,
  },
  swift: {
    label: "Swift",
    aliases: [],
    shikiLang: "swift",
    load: async () => (await import("@shikijs/langs/swift")).default,
  },
  systemd: {
    label: "Systemd Units",
    aliases: [],
    shikiLang: "systemd",
    load: async () => (await import("@shikijs/langs/systemd")).default,
  },
  "system-verilog": {
    label: "SystemVerilog",
    aliases: [],
    shikiLang: "system-verilog",
    load: async () => (await import("@shikijs/langs/system-verilog")).default,
  },
  talonscript: {
    label: "TalonScript",
    aliases: ["talon"],
    shikiLang: "talonscript",
    load: async () => (await import("@shikijs/langs/talonscript")).default,
  },
  tasl: {
    label: "Tasl",
    aliases: [],
    shikiLang: "tasl",
    load: async () => (await import("@shikijs/langs/tasl")).default,
  },
  tcl: {
    label: "Tcl",
    aliases: [],
    shikiLang: "tcl",
    load: async () => (await import("@shikijs/langs/tcl")).default,
  },
  templ: {
    label: "Templ",
    aliases: [],
    shikiLang: "templ",
    load: async () => (await import("@shikijs/langs/templ")).default,
  },
  terraform: {
    label: "Terraform",
    aliases: ["tf", "tfvars"],
    shikiLang: "terraform",
    load: async () => (await import("@shikijs/langs/terraform")).default,
  },
  tex: {
    label: "TeX",
    aliases: [],
    shikiLang: "tex",
    load: async () => (await import("@shikijs/langs/tex")).default,
  },
  toml: {
    label: "TOML",
    aliases: [],
    shikiLang: "toml",
    load: async () => (await import("@shikijs/langs/toml")).default,
  },
  tsv: {
    label: "TSV",
    aliases: [],
    shikiLang: "tsv",
    load: async () => (await import("@shikijs/langs/tsv")).default,
  },
  tsx: {
    label: "TSX",
    aliases: [],
    shikiLang: "tsx",
    load: async () => (await import("@shikijs/langs/tsx")).default,
  },
  turtle: {
    label: "Turtle",
    aliases: [],
    shikiLang: "turtle",
    load: async () => (await import("@shikijs/langs/turtle")).default,
  },
  twig: {
    label: "Twig",
    aliases: [],
    shikiLang: "twig",
    load: async () => (await import("@shikijs/langs/twig")).default,
  },
  ts: {
    label: "TypeScript",
    aliases: ["typescript", "ts", "cts", "mts"],
    shikiLang: "typescript",
    load: async () => (await import("@shikijs/langs/typescript")).default,
  },
  "ts-tags": {
    label: "TypeScript with Tags",
    aliases: ["lit"],
    shikiLang: "ts-tags",
    load: async () => (await import("@shikijs/langs/ts-tags")).default,
  },
  typespec: {
    label: "TypeSpec",
    aliases: ["tsp"],
    shikiLang: "typespec",
    load: async () => (await import("@shikijs/langs/typespec")).default,
  },
  typst: {
    label: "Typst",
    aliases: ["typ"],
    shikiLang: "typst",
    load: async () => (await import("@shikijs/langs/typst")).default,
  },
  v: {
    label: "V",
    aliases: [],
    shikiLang: "v",
    load: async () => (await import("@shikijs/langs/v")).default,
  },
  vala: {
    label: "Vala",
    aliases: [],
    shikiLang: "vala",
    load: async () => (await import("@shikijs/langs/vala")).default,
  },
  verilog: {
    label: "Verilog",
    aliases: [],
    shikiLang: "verilog",
    load: async () => (await import("@shikijs/langs/verilog")).default,
  },
  vhdl: {
    label: "VHDL",
    aliases: [],
    shikiLang: "vhdl",
    load: async () => (await import("@shikijs/langs/vhdl")).default,
  },
  viml: {
    label: "Vim Script",
    aliases: ["vim", "vimscript"],
    shikiLang: "viml",
    load: async () => (await import("@shikijs/langs/viml")).default,
  },
  vb: {
    label: "Visual Basic",
    aliases: [],
    shikiLang: "vb",
    load: async () => (await import("@shikijs/langs/vb")).default,
  },
  vue: {
    label: "Vue",
    aliases: [],
    shikiLang: "vue",
    load: async () => (await import("@shikijs/langs/vue")).default,
  },
  "vue-html": {
    label: "Vue HTML",
    aliases: [],
    shikiLang: "vue-html",
    load: async () => (await import("@shikijs/langs/vue-html")).default,
  },
  "vue-vine": {
    label: "Vue Vine",
    aliases: [],
    shikiLang: "vue-vine",
    load: async () => (await import("@shikijs/langs/vue-vine")).default,
  },
  vyper: {
    label: "Vyper",
    aliases: ["vy"],
    shikiLang: "vyper",
    load: async () => (await import("@shikijs/langs/vyper")).default,
  },
  wasm: {
    label: "WebAssembly",
    aliases: [],
    shikiLang: "wasm",
    load: async () => (await import("@shikijs/langs/wasm")).default,
  },
  wit: {
    label: "WebAssembly Interface Types",
    aliases: [],
    shikiLang: "wit",
    load: async () => (await import("@shikijs/langs/wit")).default,
  },
  wenyan: {
    label: "Wenyan",
    aliases: ["文言"],
    shikiLang: "wenyan",
    load: async () => (await import("@shikijs/langs/wenyan")).default,
  },
  wgsl: {
    label: "WGSL",
    aliases: [],
    shikiLang: "wgsl",
    load: async () => (await import("@shikijs/langs/wgsl")).default,
  },
  wikitext: {
    label: "Wikitext",
    aliases: ["mediawiki", "wiki"],
    shikiLang: "wikitext",
    load: async () => (await import("@shikijs/langs/wikitext")).default,
  },
  reg: {
    label: "Windows Registry Script",
    aliases: [],
    shikiLang: "reg",
    load: async () => (await import("@shikijs/langs/reg")).default,
  },
  wolfram: {
    label: "Wolfram",
    aliases: ["wl"],
    shikiLang: "wolfram",
    load: async () => (await import("@shikijs/langs/wolfram")).default,
  },
  xml: {
    label: "XML",
    aliases: [],
    shikiLang: "xml",
    load: async () => (await import("@shikijs/langs/xml")).default,
  },
  xsl: {
    label: "XSL",
    aliases: [],
    shikiLang: "xsl",
    load: async () => (await import("@shikijs/langs/xsl")).default,
  },
  yaml: {
    label: "YAML",
    aliases: ["yml"],
    shikiLang: "yaml",
    load: async () => (await import("@shikijs/langs/yaml")).default,
  },
  zenscript: {
    label: "ZenScript",
    aliases: [],
    shikiLang: "zenscript",
    load: async () => (await import("@shikijs/langs/zenscript")).default,
  },
  zig: {
    label: "Zig",
    aliases: [],
    shikiLang: "zig",
    load: async () => (await import("@shikijs/langs/zig")).default,
  },
} as const satisfies Record<LanguageId, LanguageDefinition>;
